export const GET_ALL_DISTRIBUTIONS = "GET_ALL_DISTRIBUTIONS"
export const GET_ALL_DISTRIBUTIONS_RESPONSE = "GET_ALL_DISTRIBUTIONS_RESPONSE"

export const GET_DISTRIBUTION_BY_PRODUCER_ID = "GET_DISTRIBUTION_BY_PRODUCER_ID"
export const GET_DISTRIBUTION_BY_PRODUCER_ID_RESPONSE = "GET_DISTRIBUTION_BY_PRODUCER_ID_RESPONSE"

export const GET_DISRIBUTION_BY_ID = "GET_DISRIBUTION_BY_ID"
export const GET_DISRIBUTION_BY_ID_RESPONSE = "GET_DISRIBUTION_BY_ID_RESPONSE"

export const EDIT_DISRIBUTION_BY_ID = "EDIT_DISRIBUTION_BY_ID"
export const EDIT_DISRIBUTION_BY_ID_RESPONSE = "EDIT_DISRIBUTION_BY_ID_RESPONSE"

export const ADD_DISTRIBUTION = "ADD_DISTRIBUTION"
export const ADD_DISTRIBUTION_RESPONSE = "ADD_DISTRIBUTION_RESPONSE"