export const CREATE_NOTE = "CREATE_NOTE"
export const CREATE_NOTE_RESPONSE = "CREATE_NOTE_RESPONSE"

export const GET_NOTE_BY_PROJECT_ID = "GET_NOTE_BY_PROJECT_ID"
export const GET_NOTE_BY_PROJECT_ID_RESPONSE = "GET_NOTE_BY_PROJECT_ID_RESPONSE"

export const EDIT_NOTES = "EDIT_NOTES"
export const EDIT_NOTES_RESPONSE = "EDIT_NOTES_RESPONSE"