export const CREATE_NOTE = "CREATE_NOTE"
export const CREATE_NOTE_RESPONSE = "CREATE_NOTE_RESPONSE"

export const GET_NOTE_BY_PROJECT_ID = "GET_NOTE_BY_PROJECT_ID"
export const GET_NOTE_BY_PROJECT_ID_RESPONSE = "GET_NOTE_BY_PROJECT_ID_RESPONSE"