export const GET_ALL_PROJECTCOST = "GET_ALL_PROJECTCOST"
export const GET_ALL_PROJECTCOST_RESPONSE = "GET_ALL_PROJECTCOST_RESPONSE"

export const GET_PROJECTCOST_BY_PRODUCER_ID = "GET_PROJECTCOST_BY_PRODUCER_ID"
export const GET_PROJECTCOST_BY_PRODUCER_ID_RESPONSE = "GET_PROJECTCOST_BY_PRODUCER_ID_RESPONSE"

export const GET_PROJECTCOST_BY_ID = "GET_PROJECTCOST_BY_ID"
export const GET_PROJECTCOST_BY_ID_RESPONSE = "GET_PROJECTCOST_BY_ID_RESPONSE"

export const EDIT_PROJECTCOST_BY_ID = "EDIT_PROJECTCOST_BY_ID"
export const EDIT_PROJECTCOST_BY_ID_RESPONSE = "EDIT_PROJECTCOST_BY_ID_RESPONSE"